name: Build and Test Project

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel  # Instalación explícita
        pip install -r requirements.txt

    - name: Verify project structure
      run: |
        echo "Verificando estructura del proyecto..."
        [ -d "src" ] || exit 1
        [ -d "docs" ] || exit 1
        [ -f "README.md" ] || exit 1
        [ -f "setup_project.py" ] || exit 1
        echo "Estructura del proyecto correcta"
    
        [ -d "src" ] || { echo "❌ Falta directorio src"; exit 1; }
        [ -d "tests" ] || { echo "❌ Falta directorio tests"; exit 1; }
        [ -f "setup.py" ] || { echo "❌ Falta setup.py"; exit 1; }
        echo "✅ Estructura del proyecto correcta"
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=src --cov-report=xml

    - name: Create build artifacts
      run: |
        python setup_project.py sdist bdist_wheel
        python setup.py sdist bdist_wheel
        ls -l dist/
        mkdir -p artifacts
        cp -r dist/* artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/