name: Test and Code Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov
        pip install black flake8 mypy
    
    - name: Run unit tests
      run: |
        pytest src/tests/ -v --cov=src --cov-report=xml
      
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
    
    - name: Run static type checking
      run: |
        mypy --ignore-missing-imports src/
    
    - name: Run linter
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting
      run: |
        black --check src/
  